// Generated from Lucide. Run scripts/generate-icons.cjs to regenerate.
import home_blue from './home_blue.png'
import home_muted from './home_muted.png'
import home_danger from './home_danger.png'
import home_green from './home_green.png'
import home_amber from './home_amber.png'
import home_white from './home_white.png'
import home_ink from './home_ink.png'
import report_blue from './report_blue.png'
import report_muted from './report_muted.png'
import report_danger from './report_danger.png'
import report_green from './report_green.png'
import report_amber from './report_amber.png'
import report_white from './report_white.png'
import report_ink from './report_ink.png'
import siren_blue from './siren_blue.png'
import siren_muted from './siren_muted.png'
import siren_danger from './siren_danger.png'
import siren_green from './siren_green.png'
import siren_amber from './siren_amber.png'
import siren_white from './siren_white.png'
import siren_ink from './siren_ink.png'
import mapPin_blue from './mapPin_blue.png'
import mapPin_muted from './mapPin_muted.png'
import mapPin_danger from './mapPin_danger.png'
import mapPin_green from './mapPin_green.png'
import mapPin_amber from './mapPin_amber.png'
import mapPin_white from './mapPin_white.png'
import mapPin_ink from './mapPin_ink.png'
import chevronRight_blue from './chevronRight_blue.png'
import chevronRight_muted from './chevronRight_muted.png'
import chevronRight_danger from './chevronRight_danger.png'
import chevronRight_green from './chevronRight_green.png'
import chevronRight_amber from './chevronRight_amber.png'
import chevronRight_white from './chevronRight_white.png'
import chevronRight_ink from './chevronRight_ink.png'
import chevronDown_blue from './chevronDown_blue.png'
import chevronDown_muted from './chevronDown_muted.png'
import chevronDown_danger from './chevronDown_danger.png'
import chevronDown_green from './chevronDown_green.png'
import chevronDown_amber from './chevronDown_amber.png'
import chevronDown_white from './chevronDown_white.png'
import chevronDown_ink from './chevronDown_ink.png'
import search_blue from './search_blue.png'
import search_muted from './search_muted.png'
import search_danger from './search_danger.png'
import search_green from './search_green.png'
import search_amber from './search_amber.png'
import search_white from './search_white.png'
import search_ink from './search_ink.png'
import shield_blue from './shield_blue.png'
import shield_muted from './shield_muted.png'
import shield_danger from './shield_danger.png'
import shield_green from './shield_green.png'
import shield_amber from './shield_amber.png'
import shield_white from './shield_white.png'
import shield_ink from './shield_ink.png'
import book_blue from './book_blue.png'
import book_muted from './book_muted.png'
import book_danger from './book_danger.png'
import book_green from './book_green.png'
import book_amber from './book_amber.png'
import book_white from './book_white.png'
import book_ink from './book_ink.png'
import clock_blue from './clock_blue.png'
import clock_muted from './clock_muted.png'
import clock_danger from './clock_danger.png'
import clock_green from './clock_green.png'
import clock_amber from './clock_amber.png'
import clock_white from './clock_white.png'
import clock_ink from './clock_ink.png'
import user_blue from './user_blue.png'
import user_muted from './user_muted.png'
import user_danger from './user_danger.png'
import user_green from './user_green.png'
import user_amber from './user_amber.png'
import user_white from './user_white.png'
import user_ink from './user_ink.png'
import arrowLeft_blue from './arrowLeft_blue.png'
import arrowLeft_muted from './arrowLeft_muted.png'
import arrowLeft_danger from './arrowLeft_danger.png'
import arrowLeft_green from './arrowLeft_green.png'
import arrowLeft_amber from './arrowLeft_amber.png'
import arrowLeft_white from './arrowLeft_white.png'
import arrowLeft_ink from './arrowLeft_ink.png'
import arrowUpRight_blue from './arrowUpRight_blue.png'
import arrowUpRight_muted from './arrowUpRight_muted.png'
import arrowUpRight_danger from './arrowUpRight_danger.png'
import arrowUpRight_green from './arrowUpRight_green.png'
import arrowUpRight_amber from './arrowUpRight_amber.png'
import arrowUpRight_white from './arrowUpRight_white.png'
import arrowUpRight_ink from './arrowUpRight_ink.png'
import camera_blue from './camera_blue.png'
import camera_muted from './camera_muted.png'
import camera_danger from './camera_danger.png'
import camera_green from './camera_green.png'
import camera_amber from './camera_amber.png'
import camera_white from './camera_white.png'
import camera_ink from './camera_ink.png'
import mic_blue from './mic_blue.png'
import mic_muted from './mic_muted.png'
import mic_danger from './mic_danger.png'
import mic_green from './mic_green.png'
import mic_amber from './mic_amber.png'
import mic_white from './mic_white.png'
import mic_ink from './mic_ink.png'
import phone_blue from './phone_blue.png'
import phone_muted from './phone_muted.png'
import phone_danger from './phone_danger.png'
import phone_green from './phone_green.png'
import phone_amber from './phone_amber.png'
import phone_white from './phone_white.png'
import phone_ink from './phone_ink.png'
import check_blue from './check_blue.png'
import check_muted from './check_muted.png'
import check_danger from './check_danger.png'
import check_green from './check_green.png'
import check_amber from './check_amber.png'
import check_white from './check_white.png'
import check_ink from './check_ink.png'
import close_blue from './close_blue.png'
import close_muted from './close_muted.png'
import close_danger from './close_danger.png'
import close_green from './close_green.png'
import close_amber from './close_amber.png'
import close_white from './close_white.png'
import close_ink from './close_ink.png'
import refresh_blue from './refresh_blue.png'
import refresh_muted from './refresh_muted.png'
import refresh_danger from './refresh_danger.png'
import refresh_green from './refresh_green.png'
import refresh_amber from './refresh_amber.png'
import refresh_white from './refresh_white.png'
import refresh_ink from './refresh_ink.png'
import send_blue from './send_blue.png'
import send_muted from './send_muted.png'
import send_danger from './send_danger.png'
import send_green from './send_green.png'
import send_amber from './send_amber.png'
import send_white from './send_white.png'
import send_ink from './send_ink.png'
import navigation_blue from './navigation_blue.png'
import navigation_muted from './navigation_muted.png'
import navigation_danger from './navigation_danger.png'
import navigation_green from './navigation_green.png'
import navigation_amber from './navigation_amber.png'
import navigation_white from './navigation_white.png'
import navigation_ink from './navigation_ink.png'
import tasks_blue from './tasks_blue.png'
import tasks_muted from './tasks_muted.png'
import tasks_danger from './tasks_danger.png'
import tasks_green from './tasks_green.png'
import tasks_amber from './tasks_amber.png'
import tasks_white from './tasks_white.png'
import tasks_ink from './tasks_ink.png'
import briefcase_blue from './briefcase_blue.png'
import briefcase_muted from './briefcase_muted.png'
import briefcase_danger from './briefcase_danger.png'
import briefcase_green from './briefcase_green.png'
import briefcase_amber from './briefcase_amber.png'
import briefcase_white from './briefcase_white.png'
import briefcase_ink from './briefcase_ink.png'
import flag_blue from './flag_blue.png'
import flag_muted from './flag_muted.png'
import flag_danger from './flag_danger.png'
import flag_green from './flag_green.png'
import flag_amber from './flag_amber.png'
import flag_white from './flag_white.png'
import flag_ink from './flag_ink.png'
import location_blue from './location_blue.png'
import location_muted from './location_muted.png'
import location_danger from './location_danger.png'
import location_green from './location_green.png'
import location_amber from './location_amber.png'
import location_white from './location_white.png'
import location_ink from './location_ink.png'
import image_blue from './image_blue.png'
import image_muted from './image_muted.png'
import image_danger from './image_danger.png'
import image_green from './image_green.png'
import image_amber from './image_amber.png'
import image_white from './image_white.png'
import image_ink from './image_ink.png'
import info_blue from './info_blue.png'
import info_muted from './info_muted.png'
import info_danger from './info_danger.png'
import info_green from './info_green.png'
import info_amber from './info_amber.png'
import info_white from './info_white.png'
import info_ink from './info_ink.png'
import logout_blue from './logout_blue.png'
import logout_muted from './logout_muted.png'
import logout_danger from './logout_danger.png'
import logout_green from './logout_green.png'
import logout_amber from './logout_amber.png'
import logout_white from './logout_white.png'
import logout_ink from './logout_ink.png'
import eye_blue from './eye_blue.png'
import eye_muted from './eye_muted.png'
import eye_danger from './eye_danger.png'
import eye_green from './eye_green.png'
import eye_amber from './eye_amber.png'
import eye_white from './eye_white.png'
import eye_ink from './eye_ink.png'
import eyeOff_blue from './eyeOff_blue.png'
import eyeOff_muted from './eyeOff_muted.png'
import eyeOff_danger from './eyeOff_danger.png'
import eyeOff_green from './eyeOff_green.png'
import eyeOff_amber from './eyeOff_amber.png'
import eyeOff_white from './eyeOff_white.png'
import eyeOff_ink from './eyeOff_ink.png'
import link_blue from './link_blue.png'
import link_muted from './link_muted.png'
import link_danger from './link_danger.png'
import link_green from './link_green.png'
import link_amber from './link_amber.png'
import link_white from './link_white.png'
import link_ink from './link_ink.png'
import plus_blue from './plus_blue.png'
import plus_muted from './plus_muted.png'
import plus_danger from './plus_danger.png'
import plus_green from './plus_green.png'
import plus_amber from './plus_amber.png'
import plus_white from './plus_white.png'
import plus_ink from './plus_ink.png'
import video_blue from './video_blue.png'
import video_muted from './video_muted.png'
import video_danger from './video_danger.png'
import video_green from './video_green.png'
import video_amber from './video_amber.png'
import video_white from './video_white.png'
import video_ink from './video_ink.png'
import settings_blue from './settings_blue.png'
import settings_muted from './settings_muted.png'
import settings_danger from './settings_danger.png'
import settings_green from './settings_green.png'
import settings_amber from './settings_amber.png'
import settings_white from './settings_white.png'
import settings_ink from './settings_ink.png'
import volume_blue from './volume_blue.png'
import volume_muted from './volume_muted.png'
import volume_danger from './volume_danger.png'
import volume_green from './volume_green.png'
import volume_amber from './volume_amber.png'
import volume_white from './volume_white.png'
import volume_ink from './volume_ink.png'

export const iconAssets: Record<string, Record<string, string>> = {
  'home': { 'blue': home_blue, 'muted': home_muted, 'danger': home_danger, 'green': home_green, 'amber': home_amber, 'white': home_white, 'ink': home_ink },
  'report': { 'blue': report_blue, 'muted': report_muted, 'danger': report_danger, 'green': report_green, 'amber': report_amber, 'white': report_white, 'ink': report_ink },
  'siren': { 'blue': siren_blue, 'muted': siren_muted, 'danger': siren_danger, 'green': siren_green, 'amber': siren_amber, 'white': siren_white, 'ink': siren_ink },
  'mapPin': { 'blue': mapPin_blue, 'muted': mapPin_muted, 'danger': mapPin_danger, 'green': mapPin_green, 'amber': mapPin_amber, 'white': mapPin_white, 'ink': mapPin_ink },
  'chevronRight': { 'blue': chevronRight_blue, 'muted': chevronRight_muted, 'danger': chevronRight_danger, 'green': chevronRight_green, 'amber': chevronRight_amber, 'white': chevronRight_white, 'ink': chevronRight_ink },
  'chevronDown': { 'blue': chevronDown_blue, 'muted': chevronDown_muted, 'danger': chevronDown_danger, 'green': chevronDown_green, 'amber': chevronDown_amber, 'white': chevronDown_white, 'ink': chevronDown_ink },
  'search': { 'blue': search_blue, 'muted': search_muted, 'danger': search_danger, 'green': search_green, 'amber': search_amber, 'white': search_white, 'ink': search_ink },
  'shield': { 'blue': shield_blue, 'muted': shield_muted, 'danger': shield_danger, 'green': shield_green, 'amber': shield_amber, 'white': shield_white, 'ink': shield_ink },
  'book': { 'blue': book_blue, 'muted': book_muted, 'danger': book_danger, 'green': book_green, 'amber': book_amber, 'white': book_white, 'ink': book_ink },
  'clock': { 'blue': clock_blue, 'muted': clock_muted, 'danger': clock_danger, 'green': clock_green, 'amber': clock_amber, 'white': clock_white, 'ink': clock_ink },
  'user': { 'blue': user_blue, 'muted': user_muted, 'danger': user_danger, 'green': user_green, 'amber': user_amber, 'white': user_white, 'ink': user_ink },
  'arrowLeft': { 'blue': arrowLeft_blue, 'muted': arrowLeft_muted, 'danger': arrowLeft_danger, 'green': arrowLeft_green, 'amber': arrowLeft_amber, 'white': arrowLeft_white, 'ink': arrowLeft_ink },
  'arrowUpRight': { 'blue': arrowUpRight_blue, 'muted': arrowUpRight_muted, 'danger': arrowUpRight_danger, 'green': arrowUpRight_green, 'amber': arrowUpRight_amber, 'white': arrowUpRight_white, 'ink': arrowUpRight_ink },
  'camera': { 'blue': camera_blue, 'muted': camera_muted, 'danger': camera_danger, 'green': camera_green, 'amber': camera_amber, 'white': camera_white, 'ink': camera_ink },
  'mic': { 'blue': mic_blue, 'muted': mic_muted, 'danger': mic_danger, 'green': mic_green, 'amber': mic_amber, 'white': mic_white, 'ink': mic_ink },
  'phone': { 'blue': phone_blue, 'muted': phone_muted, 'danger': phone_danger, 'green': phone_green, 'amber': phone_amber, 'white': phone_white, 'ink': phone_ink },
  'check': { 'blue': check_blue, 'muted': check_muted, 'danger': check_danger, 'green': check_green, 'amber': check_amber, 'white': check_white, 'ink': check_ink },
  'close': { 'blue': close_blue, 'muted': close_muted, 'danger': close_danger, 'green': close_green, 'amber': close_amber, 'white': close_white, 'ink': close_ink },
  'refresh': { 'blue': refresh_blue, 'muted': refresh_muted, 'danger': refresh_danger, 'green': refresh_green, 'amber': refresh_amber, 'white': refresh_white, 'ink': refresh_ink },
  'send': { 'blue': send_blue, 'muted': send_muted, 'danger': send_danger, 'green': send_green, 'amber': send_amber, 'white': send_white, 'ink': send_ink },
  'navigation': { 'blue': navigation_blue, 'muted': navigation_muted, 'danger': navigation_danger, 'green': navigation_green, 'amber': navigation_amber, 'white': navigation_white, 'ink': navigation_ink },
  'tasks': { 'blue': tasks_blue, 'muted': tasks_muted, 'danger': tasks_danger, 'green': tasks_green, 'amber': tasks_amber, 'white': tasks_white, 'ink': tasks_ink },
  'briefcase': { 'blue': briefcase_blue, 'muted': briefcase_muted, 'danger': briefcase_danger, 'green': briefcase_green, 'amber': briefcase_amber, 'white': briefcase_white, 'ink': briefcase_ink },
  'flag': { 'blue': flag_blue, 'muted': flag_muted, 'danger': flag_danger, 'green': flag_green, 'amber': flag_amber, 'white': flag_white, 'ink': flag_ink },
  'location': { 'blue': location_blue, 'muted': location_muted, 'danger': location_danger, 'green': location_green, 'amber': location_amber, 'white': location_white, 'ink': location_ink },
  'image': { 'blue': image_blue, 'muted': image_muted, 'danger': image_danger, 'green': image_green, 'amber': image_amber, 'white': image_white, 'ink': image_ink },
  'info': { 'blue': info_blue, 'muted': info_muted, 'danger': info_danger, 'green': info_green, 'amber': info_amber, 'white': info_white, 'ink': info_ink },
  'logout': { 'blue': logout_blue, 'muted': logout_muted, 'danger': logout_danger, 'green': logout_green, 'amber': logout_amber, 'white': logout_white, 'ink': logout_ink },
  'eye': { 'blue': eye_blue, 'muted': eye_muted, 'danger': eye_danger, 'green': eye_green, 'amber': eye_amber, 'white': eye_white, 'ink': eye_ink },
  'eyeOff': { 'blue': eyeOff_blue, 'muted': eyeOff_muted, 'danger': eyeOff_danger, 'green': eyeOff_green, 'amber': eyeOff_amber, 'white': eyeOff_white, 'ink': eyeOff_ink },
  'link': { 'blue': link_blue, 'muted': link_muted, 'danger': link_danger, 'green': link_green, 'amber': link_amber, 'white': link_white, 'ink': link_ink },
  'plus': { 'blue': plus_blue, 'muted': plus_muted, 'danger': plus_danger, 'green': plus_green, 'amber': plus_amber, 'white': plus_white, 'ink': plus_ink },
  'video': { 'blue': video_blue, 'muted': video_muted, 'danger': video_danger, 'green': video_green, 'amber': video_amber, 'white': video_white, 'ink': video_ink },
  'settings': { 'blue': settings_blue, 'muted': settings_muted, 'danger': settings_danger, 'green': settings_green, 'amber': settings_amber, 'white': settings_white, 'ink': settings_ink },
  'volume': { 'blue': volume_blue, 'muted': volume_muted, 'danger': volume_danger, 'green': volume_green, 'amber': volume_amber, 'white': volume_white, 'ink': volume_ink }
}
